### ISSUE TITLE
Is the code still open source now?

### ISSUE THREAD

**Issue by mrfengjin** [smartroboticslab/GSFusion#2]
Hi, thank you for your great work. Is the code still open source now?

**Comment by goldoak** [comment]
Thank you for your interest in our work. We submitted our paper last month, so the review results have not been released yet. We will share the code as soon as we receive positive feedback from the reviewers. We estimate that the release date will be in December or January of next year.

**Comment by mrfengjin** [comment]
thanks

**Comment by goldoak** [comment]
The code has now been released.
