### ISSUE TITLE
add new gaussian issue

### ISSUE THREAD

**Issue by whwh747** [smartroboticslab/GSFusion#3]
How can we determine which pixels in the current image should be initialized as Gaussian functions based on the quadtree? I noticed the term "contrast" mentioned in the paper; what does contrast refer to?

**Comment by goldoak** [comment]
Contrast is defined as the difference in luminance or color that makes an object in an image stand out against a background with a different luminance or color. If you still have questions about this term, please refer to the code [here](https://github.com/smartroboticslab/GSFusion/blob/main/src/gs/quad_tree.cu) for a clearer understanding.

**Comment by whwh747** [comment]
Thank you, I understand contrast now. How are the leaf nodes at different levels of the quadtree initialized as Gaussian functions?

**Comment by goldoak** [comment]
We back-project the center of a quadrant into the world coordinate frame using the depth map. For more details, please refer to our paper in Section III-B-2.
